---
title: "MOR December"
author: "Alice Tivarovsky"
date: "2025-12-04"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries and Themes

```{r libraries}
pacman::p_load(
  tidyverse,
  dbplyr,
  DBI,
  odbc, 
  lubridate,
  plotly, 
  epitools, 
  MatchIt, 
  lmtest,
  sandwich,
  broom
  
)

theme_set(theme_bw())
set.seed(1234)

# remove scientific notation
options(scipen=999)

```


## Import & Tidy Data

### Connect to Servers/Databases

```{r odbc connect}
mcanalytics <- DBI::dbConnect(odbc::odbc()
                        ,Driver = "ODBC Driver 17 for SQL Server"
                        ,Server = "DB-PROD-MSO"
                        ,Database = "MCANALYTICS"
                        ,Trusted_Connection = "Yes")

mcis <- DBI::dbConnect(odbc::odbc()
                        ,Driver = "ODBC Driver 17 for SQL Server"
                        ,Server = "SQL12"
                        ,Database = "MCIS"
                        ,Trusted_Connection = "Yes")

altamed_dwh <- DBI::dbConnect(odbc::odbc()
                        ,Driver = "ODBC Driver 17 for SQL Server"
                        ,Server = "DB-PROD-DWH"
                        ,Database = "ALTAMED_DWH"
                        ,Trusted_Connection = "Yes")

acg <- DBI::dbConnect(odbc::odbc()
                        ,Driver = "ODBC Driver 17 for SQL Server"
                        ,Server = "DB-PROD-DWH"
                        ,Database = "ACG"
                        ,Trusted_Connection = "Yes")

datalake <- DBI::dbConnect(odbc::odbc()
                        ,Driver = "ODBC Driver 17 for SQL Server"
                        ,Server = "DB-PROD-REPORT"
                        ,Database = "Datalake"
                        ,Trusted_Connection = "Yes")


```


### Import Tables

Define interval start date and end date (Sep 2024 - Sep 2025). Choose region. 

```{r}
start_date <- '2023-09-01'
end_date <- '2025-08-31'

#elig_year_month <- 202508 

region_select <- "Region 3 - Orange County"

```

Pull in ED table. 
```{r}
MOR_ED_Detail <- 
  mcis |> 
  tbl(in_schema("dbo", "MOR_ED_Detail")) |> 
  filter(Report_Include == "Report Include") |> 
  collect() |> 
  janitor::clean_names()


```

Filter and group for output.
```{r}
MOR_region <- 
  MOR_ED_Detail |> 
  filter(region == region_select)

ed_detail_grouped <- 
  MOR_region |> 
  group_by(patient_sid) |> 
  summarise(ed_visit_count = n()) 

ed_detail_grouped |> 
  arrange(desc(ed_visit_count))

# join count back to patient
MOR_region_counts <- 
  MOR_region |> 
  left_join(ed_detail_grouped, by = "patient_sid") |> 
  mutate(ed_visit_count_cat = case_when(ed_visit_count >= 1 & ed_visit_count <= 5 ~ "1-5", 
                                          ed_visit_count >5 & ed_visit_count <= 10 ~ "6-10", 
                                          ed_visit_count > 10 & ed_visit_count <= 20 ~ "10-20", 
                                          ed_visit_count > 20 & ed_visit_count <= 50 ~ "20-50", 
                                          ed_visit_count > 50 & ed_visit_count <= 100 ~ "50-100", 
                                          ed_visit_count > 100 ~ "> 100", 
                                          .default = "NA")) 

MOR_region_counts |> 
  filter(ed_visit_count > 50) |> 
  group_by(ccsr_category) |> 
  summarise(n = n()) |> 
  arrange(desc(n)) 


MOR_region_counts |> 
  group_by(ed_visit_count_cat) |>
  summarise(count = n())

```

```{r}
MOR_region_counts |> 
  filter(!is.na(ed_visit_count_cat)) |> 
  rename(ED_Visit_Count_ = ed_visit_count_cat) |> 
  ggplot(aes(x = ED_Visit_Count_, fill = ED_Visit_Count_)) + 
  geom_histogram(stat = "count")  +
  geom_text(aes(label = ED_Visit_Count_)) |> 
  labs(x = "ED Visit Count", 
       y = "Patient Count") + 
  theme(legend.position = "none")

```

Visit Reasons. 
```{r}
MOR_region_5_counts |> 
  filter(ed_visit_count > 100) |> 
  group_by(ccsr_category) |> 
  summarise(n = n()) |> 
  arrange(desc(n))

```

```{r}

```

